agent:
    # llm_model: gpt-3.5-turbo-0613
    llm-model: gpt-4-0613
    api_url: http://localhost:9502/
    user_id: ejack
    port: 9502

database:
    # username: READONLY_RA
    # password: 'RE1#AD2#RA3'
    # dbname: secure9.pristineinfotech.com:7784/RiteAid
    
    username: PRESTO_IUX
    password: 'PR#IUX#2023'
    dbname: secure2.pristineinfotech.com:7781/IUX

general:
    client_name: "RA"
    data_url: 'http://secure1.pristineinfotech.com:7200/presto-data-services'
    authentication_url: 'https://secure7.pristineinfotech.com/PrestoAnalyticsDemo/OfferManagement/Ajax/Common.asmx/AuthenticateUser'
    recommendation_service_url: 'https://secure7.pristineinfotech.com/PrestoAnalyticsDemo/OfferManagement/Ajax/Common.asmx/ExecutePriceRecommendationQR'
    completeRevieweview_url: 'https://secure7.pristineinfotech.com/PrestoAnalyticsDemo/OfferManagement/Ajax/QuarterlyPriceReview.asmx/CompleteReviewIUX'
    chain_id: 52
    global_zone_id: 483
    all_prod_id: 9491
    n_responses: 1
    cache: False
    port: 9502
    log_filename: 'E:/Users/Pradeep/Logs/dev-logs.log'    
open-ai:
    open_ai_key: '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'
   
kvi:
    kvi_url: 'http://127.0.0.1:6999/'    

router:
  llm-model: gpt-4-0613
  store: http://localhost:9502/query_store_llm
  kvi: http://localhost:9502/getKVI
  ### for the time being, the financials-agent is hosted on the same server of router
  sales: http://localhost:9502/query
  affinity: http://localhost:9502/getAffinity
  price_index: http://localhost:9502/priceindexllm
  recommend-review-approve: http://localhost:9502/recommend-review-approve-service
  bpr: http://localhost:9502/query-bpr
  port: 9502
  timeout: 30
  